### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by 594cp** [sergehog/FW-DIBR#1]
Hi, thanks for your working, I am interested in it. 
Can you give a link of your paper? Because I can not find it and can you give more usages of your code?
And I wonder if your code have the function to transform a map and a depth map to one left image and one right image, cause I can not find one suitable code in web. I will be glad if you reply!

**Comment by sergehog** [comment]
Hi there, 
Link is here (I also updated README), but the article is not open
https://doi.org/10.1117/1.JEI.28.1.013049

Not sure, what do you mean by "transform.. " 
You want to render stereoscopic image out of View+Depth (RGB+D) Image? 
This code in here is research-oriented one, it would be hard to apply it for real images, but you can try
