### ISSUE TITLE
recursive-gaussian function not present.

### ISSUE THREAD

**Issue by RafiaMansoor** [sergehog/FW-DIBR#2]
The recursive gaussian function is not available in the code you provided. Can you please see to it and upload that because without that the code will not work.

**Comment by sergehog** [comment]
Apologize for inconvenience. I will try to find a binary and upload it here. 
But if you have access to Windows, MS Visual Studio and Matlab you may try to compile this binary yourself. 
The code is available in my other repo: https://github.com/sergehog/MEX/tree/master/recursive_gaussian

**Comment by sergehog** [comment]
please check again now

**Comment by RafiaMansoor** [comment]
If it is convenient for you can you please send me the function recursive_Gaussian.m file.
In your code the mat lab file of recursive_Gaussian is not present.

**Comment by sergehog** [comment]
It's now provided as MEXW64 binary, not as M-file. It is in the "lib" directory https://github.com/sergehog/FW-DIBR/tree/master/lib

**Comment by annzheng** [comment]
@sergehog I found there is no function "get_learning_laplacian" and "getGMatByMask", could you please upload them?
